### ISSUE TITLE
Implement a better way to mark tests as skipped/optional

### ISSUE THREAD

**Issue by SaschaMann** [exercism/xjulia#45]
Currently there is no way for Travis to test an example solution against `@test_skip`-tests. This would be very useful to have for exercises with language specific or bonus exercises such as #44.

**Comment by andrej-makarov-skrt** [comment]
May it help?
`macro test_skip(ex, kws...)
           orig_ex = Expr(:inert, ex)
           testres = :(Base.Test.Pass(:skipped, $orig_ex, nothing, nothing))
           :(Base.Test.record(Base.Test.get_testset(), $testres))
       end`

**Comment by SaschaMann** [comment]
```julia
julia> macro skip_test(ex, kws...)
           orig_ex = Expr(:inert, ex)
           testres = :(Base.Test.Pass(:skipped, $orig_ex, nothing, nothing))
           :(Base.Test.record(Base.Test.get_testset(), $testres))
       end
@skip_test (macro with 1 method)

julia> @testset "blubb" begin
           @test 1 == 1
           @skip_test f(3) = 2
       end;
Test Summary: | Pass  Total
  blubb       |    2      2
```

I don't think skipped tests should be marked as `Pass` but they shouldn't throw an error either.

A macro that runs the tests and marks them as `Broken` if there are errors, but passes them if it works would be ideal. Neither `@test_skip` or `@test_broken` work that way unfortunately.

Something along the lines of

```julia
try
    @test bonus("foo") == "bar"
catch
    @test_skipped bonus("foo") == "bar" # or @test_broken?
end
```

If `bonus` exists and works (which it does in `example.jl`!), the test will pass normally, if not, it will be marked as skipped.

Ideally this would be a macro `@skip_test` (to avoid clashing with `@test_skip`) so that a user can easily change it to just `@test_skip` if he wants to work on the bonus exercises.

**Comment by andrej-makarov-skrt** [comment]
```julia
julia> macro skip_test(ex, kws...)
                  orig_ex = Expr(:inert, ex)
                  testres = :(Base.Test.Broken(:skipped, $orig_ex))
                  :(Base.Test.record(Base.Test.get_testset(), $testres))
end
@skip_test (macro with 1 method)

julia> @skip_test (1/0)==(0/1)
Test Broken
  Skipped: 1 / 0 == 0 / 1
```

**Comment by andrej-makarov-skrt** [comment]
In fresh Julia @test_skip should work fine marking skipped tests as broken:
https://github.com/JuliaLang/julia/blob/5151271f7d0a12bdfecac496c5f46959d8679252/base/test.jl#L661

Can't find the commit where this line was changed.

**Comment by SaschaMann** [comment]
@andrej-makarov-skrt ah okay, that's good. In that case, we can just comment out the code in question for now and change to `@test_skip` when v0.6 has been released which should happen relatively soon.

However, the [developer-testsuite](https://github.com/exercism/xjulia/blob/master/runtests.jl) should still run those tests against the `example.jl`-file, because the example needs to provide a full solution that also covers examples. This could be done with a replacement that changes `@test_skip` to `@test` in the [temporary file](https://github.com/exercism/xjulia/blob/master/runtests.jl#L15-L17) or do you have a better idea?
